---
title: "HW1"
author: "YuechenLiu"
date: "9/18/2020"
output: github_document
---

```{r}
library(tidyverse)
```
###HW1 Problem1
Create a data frame with the specified elements

```{r}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame/

```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r}
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)

```

###HW1 Problem2
```{r}
data("penguins", package = "palmerpenguins")
nrow(penguins)
ncol(penguins)
mean(penguins$flipper_length_mm, na.rm=TRUE)
###inline description: the data is about informations of penguins, important variable include: "species" "island" "bill_length_mm" "bill_depth_mm" "flipper_length_mm" "body_mass_g"  "sex" "year". The dataset has 344 rows and 8 columns. The mean flipper length is 200.9152mm.
ggplot(penguins,aes(x=bill_length_mm, y=flipper_length_mm, na.rm = TRUE, color=species))+geom_point()
ggsave(file="penguins.png")
```